export class userdata
{
    name:string;
    email:string;
    company:string;
    position:string;
    q1:number;
    q2:number;
    q3:number;
    q4:number;
    q5:number;
    q6:number;
    q7:number;
    q8:number;
    q9:number;
    q10:number;
    q11:number;
    q12:number;
    q13:number;
    q14:number;
    q15:number;
    remark:string;
    convert:string="yes";
}